export enum NotificationTypeEnum {
  INVITE_USER_JOIN_CLASS = 'INVITE_USER_JOIN_CLASS',
  NONE = 'NONE',
  REPORT_CREATED = 'REPORT_CREATED',
  STREAK_REMINDER = 'STREAK_REMINDER',
  REMOVED_FROM_CLASS = 'REMOVED_FROM_CLASS',
}
